# Generated by Django 3.2.6 on 2021-08-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'В процессе'), ('Resolved', 'Готово'), ('Error', 'Ошибка')], default='Pending', editable=False, max_length=25),
        ),
    ]
