# Generated by Django 3.2.6 on 2021-08-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0002_auto_20210819_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='key_skills',
            field=models.JSONField(null=True),
        ),
    ]
