# Generated by Django 3.2.6 on 2021-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0003_auto_20210809_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='link',
            field=models.CharField(default='google.ru', max_length=200),
            preserve_default=False,
        ),
    ]
