# Generated by Django 3.2.6 on 2021-09-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0003_auto_20210831_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hhscarper.request')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date of change')),
            ],
            options={
                'db_table': 'hhscarper_diff_report',
            },
        ),
    ]
