# Generated by Django 3.2.6 on 2021-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0003_alter_vacancy_key_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='keyword',
            field=models.CharField(max_length=100, unique=True, verbose_name='ключевое слово'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
    ]
