# Generated by Django 3.2.6 on 2021-08-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0004_vacancy_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_value', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'В процессе'), ('Resolved', 'Готово')], default='Pending', max_length=25)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date of change')),
            ],
            options={
                'verbose_name': 'запрос',
                'verbose_name_plural': 'запросы',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hhscarper.request'),
            preserve_default=False,
        ),
    ]
