# Generated by Django 3.2.6 on 2021-09-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0004_diffreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiffReport',
        ),
    ]
