# Generated by Django 3.2.6 on 2021-08-21 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0005_auto_20210821_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date of change'),
        ),
        migrations.AlterModelTable(
            name='vacancyrequest',
            table='vacancy_request',
        ),
    ]
