# Generated by Django 3.2.6 on 2021-08-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0006_auto_20210821_1613'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancyrequest',
            table='hhscarper_vacancy_request',
        ),
    ]
