# Generated by Django 3.2.6 on 2021-08-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0006_alter_vacancy_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='search_value',
            new_name='keyword',
        ),
    ]
