# Generated by Django 3.2.6 on 2021-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0007_rename_search_value_request_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'В процессе'), ('Resolved', 'Готово')], default='Pending', editable=False, max_length=25),
        ),
    ]
