# Generated by Django 3.2.6 on 2021-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0007_alter_vacancyrequest_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='request',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requests',
            field=models.ManyToManyField(through='hhscarper.VacancyRequest', to='hhscarper.Request'),
        ),
    ]
