# Generated by Django 3.2.6 on 2021-08-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0009_skillreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillreport',
            name='id',
        ),
        migrations.AlterField(
            model_name='skillreport',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hhscarper.request'),
        ),
    ]
