# Generated by Django 3.2.6 on 2021-08-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0009_auto_20210813_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='time',
        ),
    ]
