# Generated by Django 3.2.6 on 2021-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0010_remove_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
