# Generated by Django 3.2.6 on 2021-08-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0010_auto_20210822_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillReport',
        ),
    ]
