# Generated by Django 3.2.6 on 2021-08-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0012_skillreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillReport',
        ),
    ]
