# Generated by Django 3.2.6 on 2021-08-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0014_skillreport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skillreport',
            table='skill_report',
        ),
    ]
