# Generated by Django 3.2.6 on 2021-08-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0015_alter_skillreport_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skillreport',
            table='hhscarper_skill_report',
        ),
    ]
