# Generated by Django 3.2.6 on 2021-08-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0016_alter_skillreport_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'запрос', 'verbose_name_plural': 'запросы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
    ]
