# Generated by Django 3.2.6 on 2021-08-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhscarper', '0018_wordreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordReport',
        ),
    ]
